name: "dbt_snow_utils"
version: "1.0.0"
config-version: 2
require-dbt-version: ">=0.18.0"

vars:
  # Valid values are string "ALL" OR list of databases
  pipe_databases: "ALL"
  filter_by_date: 
  pipe_copy_history_filter_key: "hours"
  pipe_copy_history_filter_value: -28
  pipe_usage_history_filter_key: "hour"
  pipe_usage_history_filter_value: -28
  query_history_filter_key: "hours"
  query_history_filter_value: -28
  query_history_result_limit: 10000

# Config indicated by + and applies to all files under models
models:
  dbt_snow_utils:
    +materialized: table
    staging:
      +schema: staging
      +materialized: view
    dw:
      +schema: utils
      +materialized: incremental